# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
