# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assistantprofile_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLTASpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
