# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 13:03
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sltaspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sltaspot',
            name='geom',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
