# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sltaspot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sltaspot',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
