# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 05:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20180824_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='etiology',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='guardian',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ownerpatient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='slt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slt', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='slta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.AssistantProfile'),
            preserve_default=False,
        ),
    ]
