# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180824_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='guardian',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to=settings.AUTH_USER_MODEL),
        ),
    ]
