# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180824_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='etiology',
            field=models.TextField(blank=True),
        ),
    ]
