# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_patientprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='slta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slta', to='main.AssistantProfile'),
        ),
    ]
