# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180824_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
