# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_assistantprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantprofile',
            name='bio',
        ),
    ]
