# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_assistantprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantprofile',
            name='email',
        ),
    ]
